# Numpy

### Arrays

In [1]:
import numpy as np

In [2]:
# Transforme any list in Array

my_list = [1,2,3]

arr = np.array(my_list)

In [9]:
# See the difference between List and Array
arr

array([1, 2, 3])

In [10]:
my_list

[1, 2, 3]

In [21]:
# Matriz Array
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [22]:
arr_mat = np.array(my_mat)
arr_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
# Why transform in Array the Matriz???
# Because you can use some properties
# For exemplo:

In [27]:
arr_mat[:,0] # Columns 0

array([1, 4, 7])

In [29]:
arr_mat[:,1] # Columns 1

array([2, 5, 8])

In [28]:
arr_mat[:,2] # Columns 2

array([3, 6, 9])

In [32]:
arr_mat[0,0] # Element of  Columns 0 Row 0

1

In [35]:
arr_mat[2,2] # Element of  Columns 2 Row 2

9

In [28]:
arr_mat[:,2] # Columns 2

array([3, 6, 9])

In [36]:
arr_mat[0] # Rows 0

array([1, 2, 3])

In [37]:
arr_mat[1] # Rows 1

array([4, 5, 6])

In [64]:
# Shows up the shape of matrix
arr_mat.shape

(3, 3)

In [ ]:
# Random with Numpy

In [40]:
np.random.randn(3)

array([ 1.47361832, -0.7716407 , -0.01565711])

In [42]:
 np.random.rand(3) # between 0 - 1

array([0.30826511, 0.54115459, 0.54162563])

In [44]:
np.random.randn(4,2) # Collumns and Rows

array([[ 0.25563972, -0.45940712],
       [ 0.17682986,  1.4841106 ],
       [ 0.23409591,  2.21190703],
       [ 0.53205167, -0.96411812]])

In [46]:
np.random.randint(1,100,5) # between 1 to 100

array([16, 32, 23, 34, 36])

In [ ]:
# Reshape (remodelar) a Matrix

In [48]:
x = np.arange(0,10,1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
# Reshape
x.reshape(5,2) # 5 Columns and 2 rows

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [52]:
# Maximum and Minimum

In [51]:
x.max()

9

In [53]:
x.min()

0

In [55]:
# Show up the greatest element index
y = [1,2,3,4,100,0]
y_new = np.array(y)
y_new.argmax()

4

In [57]:
# Show up the smalest element index
y_new.argmin()

5

In [58]:
# IT'S SO HELPFULL DAILY
y_new[3::]

array([  4, 100,   0])

In [60]:
# Working with Dict
d = {
    'numbers':np.arange(0,12).reshape(4,3)
}

In [61]:
d['numbers']

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [62]:
d['numbers'].shape # Shows up the Matrix shape

(4, 3)

In [65]:
d['numbers'][:,2]

array([ 2,  5,  8, 11])

# Numpy Operations

In [99]:
x = [0,1,2]
x = np.array(x) # Need to transform in Array

In [93]:
x*x

array([1, 4, 9])

In [97]:
x**2

array([1, 4, 9])

In [94]:
x-1

array([0, 1, 2])

In [95]:
x+1

array([2, 3, 4])

In [100]:
np.sin(x)

array([0.        , 0.84147098, 0.90929743])

In [101]:
np.cos(x)

array([ 1.        ,  0.54030231, -0.41614684])